actions:
  echoaction: echo '{0}' > {1}
  pre:
    vim-plug-install: test -e ~/.vim/autoload/plug.vim || (mkdir -p ~/.vim/autoload;
      curl -fLo ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim)
  st-test: echo "TEST"
  vim-plug: vim +PlugInstall +qall
  zsh-fzf: ~/i3wm/zsh/plugins/fzf/install
config:
  backup: false
  banner: false
  create: false
  dotpath: .
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_config:
    actions:
    - echoaction "i3 config installed" /tmp/i3wm_install.log
    dst: ~/.config/i3/config
    link: link
    src: i3/config
  f_gitconfig:
    actions:
    - echoaction "gitconfig installed" /tmp/i3wm_install.log
    dst: ~/.gitconfig
    link: link
    src: .gitconfig
  f_polybar_config:
    actions:
    - echoaction "polybar config installed" /tmp/i3wm_install.log
    dst: ~/.config/polybar/config
    link: link
    src: polybar/config
  f_tmux.conf:
    actions:
    - echoaction "tmux config installed" /tmp/i3wm_install.log
    dst: ~/.tmux.conf
    link: link
    src: ./tmux.conf
  f_vimrc:
    actions:
    - vim-plug-install
    - vim-plug
    - echoaction "vim-plug and vim installed" /tmp/i3wm_install.log
    dst: ~/.vimrc
    link: link
    src: vim/vimrc
  f_xbindkeysrc:
    actions:
    - echoaction "xbindkeysrc installed" /tmp/i3wm_install.log
    dst: ~/.xbindkeysrc
    link: link
    src: X/xbindkeysrc
  f_xinitrc:
    actions:
    - echoaction "xinitrc installed" /tmp/i3wm_install.log
    dst: ~/.xinitrc
    link: link
    src: X/xinitrc
  f_xmodmap:
    actions:
    - echoaction "xmodmap installed" /tmp/i3wm_install.log
    dst: ~/.Xmodmap
    link: link
    src: X/xmodmap
  f_zshrc:
    actions:
    - zsh-fzf
    - echoaction "zshrc installed" /tmp/i3wm_install.log
    dst: ~/.zshrc
    link: link
    src: zsh/zshrc
profiles:
  all:
    dotfiles:
    - ALL
  gui:
    dotfiles:
    - f_polybar_config
    - f_config
    - f_xbindkeysrc
    - f_xinitrc
    - f_xmodmap
  headless:
    dotfiles:
    - f_vimrc
    - f_zshrc
    - f_gitconfig
    - f_xbindkeysrc
    - f_xinitrc
    - f_tmux.conf
  vim:
    dotfiles:
    - f_vimrc
